name: Release

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/**/VERSION'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.13.2'
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        cache: pip
    - name: Get changed files
      id: changed_files
      uses: tj-actions/changed-files@v2.0.0
    - name: Install Python Deps
      run: pip install -r requirements.txt
    - name: Build Package webfont-lxgw-wenkai-lite
      if: contains(steps.changed_files.outputs.all_changed_files, 'packages/webfont-lxgw-wenkai-lite/VERSION')
      run: npm run build:package -- webfont-lxgw-wenkai-lite
    - name: Build Package webfont-lxgw-wenkai-screen
      if: contains(steps.changed_files.outputs.all_changed_files, 'packages/webfont-lxgw-wenkai-screen/VERSION')
      run: npm run build:package -- webfont-lxgw-wenkai-screen
    - name: Build Package webfont-lxgw-wenkai-tc
      if: contains(steps.changed_files.outputs.all_changed_files, 'packages/webfont-lxgw-wenkai-tc/VERSION')
      run: npm run build:package -- webfont-lxgw-wenkai-tc
    - name: Build Package webfont-lxgw-wenkai
      if: contains(steps.changed_files.outputs.all_changed_files, 'packages/webfont-lxgw-wenkai/VERSION')
      run: npm run build:package -- webfont-lxgw-wenkai
    - name: Run Semantic Release
      run: npm run release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
