name: Upstream Monitor
on:
  workflow_dispatch:
  schedule:
  - cron: '0 */3 * * *'

jobs:
  upstream_check:
    name: Upstream Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        cache: pip
    - name: Install Python Deps
      run: pip install -r requirements.txt
    - name: Run Check Script
      run: npm run build
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: 'feat(deps): update font version'
        author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        title: 'feat(deps): update font version'
        delete-branch: true
        branch-suffix: short-commit-hash
